import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
// import { ThemeProvider } from "@/components/theme-provider";

const poppinsMono = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppinsMono.className} h-full antialiased`}>
      <body
        className="min-h-full flex flex-col"
        suppressHydrationWarning={true}
      >
        {children}
      </body>
    </html>
  );
}
